Update Syrian Flag to the Green Flag
hjnilsson/country-flags pull request #153
Opened 2024-12-24 16:24 UTC by JamelSyr

Syria has officially adopted the green flag after its liberation. This pull request updates the flag to reflect the current reality. For more details, see [Wikipedia](https://en.wikipedia.org/wiki/Flag_of_Syria)

2024-12-24 19:25 UTC, wyattoday commented
Thanks!  I'll address this after Christmas.

2025-01-08 07:27 UTC, JamelSyr commented
Hi, Any updates?

2025-01-09 19:01 UTC, mhamdeh-visualis requested changes
@JamelSyr  Could you please replace the flags with the appropriate dimensions?

2025-01-09 19:01 UTC, mhamdeh-visualis commented on svg/sy.svg
@JamelSyr  Could you please replace the flag with the appropriate dimensions?

2025-01-09 23:45 UTC, JamelSyr commented on svg/sy.svg
Done

2025-01-09 23:46 UTC, JamelSyr commented
i update it

2025-08-05 15:04 UTC, lukaspluemper commented
Hi, any news here?
Looking at wikipedia most major operation systems have adopted the new flag in the meantime.
https://en.wikipedia.org/wiki/Flag_of_Syria

2026-03-10 18:16 UTC, closed without merging

2026-03-10 18:18 UTC, wyattoday commented
Thanks, updated with docs to legislation.